# Generated by Django 6.0.4 on 2026-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
